language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop"
  - secure: "iNgQIHnu/y0XxNXS7lDuMhROFxDQAdcm4aYyLPAxa7FEHupYVFokx9CLfyY9rjmqMmKGAbbyUgF26uxK8TQLC3XYAMbIUuYoL6yEBcSF3kpbwNJ/To5XSa2v1yR6kh+ACMMxyTffB/GgtRr/OCBzVIyy+7vL5hzKxuq1cSYL3CTpV1LTdHYnXxinxO0xxj/X/02svBlHHOgHK9aJAlBZbYJHCVk82L2sCPJMzMALRcow+rZqAvZS0pHmmIHxxYrsWEwstNiG50zPe13C3l7xgfP5OeHoeWxlLbbMt+cexg1KNVRaWHd9NHErRfxPty5iUfeQcYqPmHyMVWD21fyzooUEkimSWiJ473IGCp2hYvg4eLALjjpyG/V5uAXHGm7yHM37SPjQv2dAkqTFc4hCasw9y7uuzS5GfxEQGQNXGp3HkhkeY/3qhUEHDdRv6Q5Y5cJyNBF7lFMdZasEq8YhH42FVmA2poCro6h8tXfMxpgGm+5SiPyM5kc8q82Y69K8nz/UQZSmOtGwd+6fp2xJWqz8iEmbD30kpvL52hmMaYDV+6O/cUL9+w4E57FD8qWhinxqFdMV1/5X1miygfxpTWGLVIcVH2DLCJQW/zEGtRaQmdN2h+RGkWwCwK6tVOb1juew1cLBpmSHzdKmvuM8gl0YjhPHwmsuA8CwzUWDhYo="
  - secure: "zZswql2GRrJR0CSoqXrnhyO+Fj8wRqrYgH6vVmFUaGNyun98r717h6wBadA0VGlV5xYfdO+AodtzPI7WZWOU/VWPprvzsPjIXSt7ju7A9Dccm3rO6bSsl3vdydB5XPBsT+Qp6bM0HEATW0yXllcjBwqneF8sCp6ZkDYXJpX7+5dlymiFXfXFcLcB2DuBVbHwo68LEQC9kiDdrdbiNZgf8oHZNiWIbfV82cvy/ZSPtstKFPoKqBOqfvSX5fl0Md/JJf5D+1HPH4LE7P8B+/J6YwDbzUr1xpvfxTTelGUVN1XqihpQY1hy1/3W2fCLwLIRGqoxGEyZAkAfZ8NaX8lcp8XnBojESc5O94i1DSsG5RUIrDDDMO3anAlT37CPoll6M72hcIEPRDL7xaB/fRNKXWPHlyntfzjwO3VdV40XSWvjbZuv4ynb4OjxhLOOWF1SnWOY4xr0a/uNezRHowRjsQ0T9Gre4J98nteLtOvGUhE7F8TZ8KhbgFtcoMDSJrADR+PtInrmR+uZnlP+t/z/YnlbdmSMtnTOJjFevIsLmGdP2VDCK+L+WJ6L6vGmWzCu8abDzy1A8BFASi4l9X+WNVBBtWS6OlHRzm0yFwU2H/noW122+66C/9aJ8kg6SRT91MqWr4MpzZBofYUgdL7YY5So6pE8Z7JYvLsQ1BLDyok="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs annon.status.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- "./bin/ci/push.sh"
