language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
notifications:
  slack: 
    rooms:
      - secure: "WQ3Slror3sGHDiVazkXSuFpL3fK1Wr+Vfp+Dn2rIuRLG2DFCLHA1eN9V9XCdYxN1K+5Mx3brv/mh0q18xRAXvIsJ2BVRYLIv9oxUSl9J1+JrQTJ8lICHhVLTFNgqS5q96BF+KEMvd6CEiD5TyATHmtyhdJeBZs/9Rzvqub2xA/nBbLdefUgHtpBc2256enRgFSoWTS8a1F1pPSb9U+aNztFN1LvaSHZ3HPK8HPi3Eba3V1jm1z1yOdSkN9GPfXwriSwrrnh8hX3mnpdCjgSfC++ASjWJGdiLevwwHZqmwm1A4c1NV9vVRr9uCJ51TLnlriJZWKNJ5oIUuoVroo0CqkNRzojKrQYKJaaMCDstX5ELylpuds9sYxsl6MTttpGSYwW+l8Z8oLkFZ3CvNDCK7JwuBmYr65VpKlUdhs33X9iNZYEnwdR91t8DNm2CI/20qPkuXCp5Ex9qoN5xxBh+kQq62YfyCByecP3e9VxhoiH/Iavo50aEVngkuE+vox+lMDyoF0AercKd6nmDRmIH62mZjYZv1YTWruGRmzDF+icipjzeLBZ5kNC6gvsXVgnNNAm3Oxd2FiCOsFJHQtQlUmojZLYrTtzZcaXbb+9cJkMXmrLzGDuSsJwXJFGdNrP7IH9JkMiieGqyGHddwobvTbyQgtotZigQhGP8l4yGEaU="
    on_success: always
env:
  global:
  - Chart=fe
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop"
  - secure: "iNgQIHnu/y0XxNXS7lDuMhROFxDQAdcm4aYyLPAxa7FEHupYVFokx9CLfyY9rjmqMmKGAbbyUgF26uxK8TQLC3XYAMbIUuYoL6yEBcSF3kpbwNJ/To5XSa2v1yR6kh+ACMMxyTffB/GgtRr/OCBzVIyy+7vL5hzKxuq1cSYL3CTpV1LTdHYnXxinxO0xxj/X/02svBlHHOgHK9aJAlBZbYJHCVk82L2sCPJMzMALRcow+rZqAvZS0pHmmIHxxYrsWEwstNiG50zPe13C3l7xgfP5OeHoeWxlLbbMt+cexg1KNVRaWHd9NHErRfxPty5iUfeQcYqPmHyMVWD21fyzooUEkimSWiJ473IGCp2hYvg4eLALjjpyG/V5uAXHGm7yHM37SPjQv2dAkqTFc4hCasw9y7uuzS5GfxEQGQNXGp3HkhkeY/3qhUEHDdRv6Q5Y5cJyNBF7lFMdZasEq8YhH42FVmA2poCro6h8tXfMxpgGm+5SiPyM5kc8q82Y69K8nz/UQZSmOtGwd+6fp2xJWqz8iEmbD30kpvL52hmMaYDV+6O/cUL9+w4E57FD8qWhinxqFdMV1/5X1miygfxpTWGLVIcVH2DLCJQW/zEGtRaQmdN2h+RGkWwCwK6tVOb1juew1cLBpmSHzdKmvuM8gl0YjhPHwmsuA8CwzUWDhYo="
  - secure: "zZswql2GRrJR0CSoqXrnhyO+Fj8wRqrYgH6vVmFUaGNyun98r717h6wBadA0VGlV5xYfdO+AodtzPI7WZWOU/VWPprvzsPjIXSt7ju7A9Dccm3rO6bSsl3vdydB5XPBsT+Qp6bM0HEATW0yXllcjBwqneF8sCp6ZkDYXJpX7+5dlymiFXfXFcLcB2DuBVbHwo68LEQC9kiDdrdbiNZgf8oHZNiWIbfV82cvy/ZSPtstKFPoKqBOqfvSX5fl0Md/JJf5D+1HPH4LE7P8B+/J6YwDbzUr1xpvfxTTelGUVN1XqihpQY1hy1/3W2fCLwLIRGqoxGEyZAkAfZ8NaX8lcp8XnBojESc5O94i1DSsG5RUIrDDDMO3anAlT37CPoll6M72hcIEPRDL7xaB/fRNKXWPHlyntfzjwO3VdV40XSWvjbZuv4ynb4OjxhLOOWF1SnWOY4xr0a/uNezRHowRjsQ0T9Gre4J98nteLtOvGUhE7F8TZ8KhbgFtcoMDSJrADR+PtInrmR+uZnlP+t/z/YnlbdmSMtnTOJjFevIsLmGdP2VDCK+L+WJ6L6vGmWzCu8abDzy1A8BFASi4l9X+WNVBBtWS6OlHRzm0yFwU2H/noW122+66C/9aJ8kg6SRT91MqWr4MpzZBofYUgdL7YY5So6pE8Z7JYvLsQ1BLDyok="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint  || travis_terminate 1
- "./bin/version-increment.sh  || travis_terminate 1"
- "./bin/build.sh  || travis_terminate 1"
- "./bin/start.sh  || travis_terminate 1"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs annon.status.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
- "./bin/ci/push.sh"
- openssl aes-256-cbc -K $encrypted_de269c7740bd_key -iv $encrypted_de269c7740bd_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
- sudo ./bin/deploy.sh || travis_terminate 1
